BEGIN EXECUTE IMMEDIATE 'DROP TABLE saved_searches CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE analytics_daily CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE search_logs CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE price_history CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE notifications CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE comparisons CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE wishlist CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE agent_reviews CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE transactions CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE bookings CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE property_amenities CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE amenities CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE property_images CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE properties CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE locations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE property_types CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE agents CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE roles CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE roles (
    id NUMBER PRIMARY KEY,
    roleName VARCHAR2(50) NOT NULL UNIQUE,
    roleDescription VARCHAR2(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    roleId NUMBER NOT NULL,
    fullname VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    phone VARCHAR2(50),
    profileImage VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'active',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE agents (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL UNIQUE,
    agencyName VARCHAR2(255),
    licenseNo VARCHAR2(100),
    experienceYears NUMBER DEFAULT 0,
    about VARCHAR2(1000),
    rating NUMBER(3,2) DEFAULT 0.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agents_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE property_types (
    id NUMBER PRIMARY KEY,
    typeName VARCHAR2(100) NOT NULL UNIQUE,
    typeDescription VARCHAR2(500),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE locations (
    id NUMBER PRIMARY KEY,
    parentLocationId NUMBER,
    areaName VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100),
    country VARCHAR2(100) DEFAULT 'Bangladesh',
    latitude NUMBER(10,8),
    longitude NUMBER(11,8),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_locations_parent FOREIGN KEY (parentLocationId) REFERENCES locations(id) ON DELETE SET NULL
);

CREATE TABLE properties (
    id NUMBER PRIMARY KEY,
    ownerId NUMBER NOT NULL,
    agentId NUMBER,
    typeId NUMBER NOT NULL,
    locationId NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    propDescription CLOB,
    price NUMBER(15,2) NOT NULL,
    areaSize NUMBER(10,2) NOT NULL,
    bedrooms NUMBER DEFAULT 0,
    bathrooms NUMBER DEFAULT 0,
    furnishedStatus VARCHAR2(50) DEFAULT 'unfurnished',
    parking NUMBER DEFAULT 0,
    balcony NUMBER DEFAULT 0,
    lift NUMBER DEFAULT 0,
    swimmingPool NUMBER DEFAULT 0,
    petFriendly NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'available',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_properties_owner FOREIGN KEY (ownerId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_properties_agent FOREIGN KEY (agentId) REFERENCES agents(id) ON DELETE SET NULL,
    CONSTRAINT fk_properties_type FOREIGN KEY (typeId) REFERENCES property_types(id) ON DELETE CASCADE,
    CONSTRAINT fk_properties_location FOREIGN KEY (locationId) REFERENCES locations(id) ON DELETE CASCADE
);

CREATE TABLE property_images (
    id NUMBER PRIMARY KEY,
    propertyId NUMBER NOT NULL,
    imagePath VARCHAR2(500) NOT NULL,
    isMain NUMBER DEFAULT 0,
    displayOrder NUMBER DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_images_property FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE
);

CREATE TABLE amenities (
    id NUMBER PRIMARY KEY,
    amenityName VARCHAR2(100) NOT NULL UNIQUE,
    icon VARCHAR2(100),
    category VARCHAR2(100),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE property_amenities (
    propertyId NUMBER NOT NULL,
    amenityId NUMBER NOT NULL,
    PRIMARY KEY (propertyId, amenityId),
    CONSTRAINT fk_prop_amenities_prop FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_prop_amenities_amenity FOREIGN KEY (amenityId) REFERENCES amenities(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    propertyId NUMBER NOT NULL,
    agentId NUMBER,
    bookingType VARCHAR2(50) NOT NULL,
    visitDate TIMESTAMP,
    startDate DATE,
    endDate DATE,
    guests NUMBER DEFAULT 1,
    status VARCHAR2(50) DEFAULT 'pending',
    totalAmount NUMBER(15,2) DEFAULT 0.00,
    notes VARCHAR2(1000),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_property FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_agent FOREIGN KEY (agentId) REFERENCES agents(id) ON DELETE SET NULL
);

CREATE TABLE transactions (
    id NUMBER PRIMARY KEY,
    bookingId NUMBER NOT NULL,
    transactionType VARCHAR2(50) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    paymentMethod VARCHAR2(50) NOT NULL,
    transactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    referenceNo VARCHAR2(100) UNIQUE,
    status VARCHAR2(50) DEFAULT 'pending',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_booking FOREIGN KEY (bookingId) REFERENCES bookings(id) ON DELETE CASCADE
);

CREATE TABLE reviews (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    propertyId NUMBER NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    comments VARCHAR2(1000),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reviews UNIQUE (userId, propertyId),
    CONSTRAINT fk_reviews_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_property FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE
);

CREATE TABLE agent_reviews (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    agentId NUMBER NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    comments VARCHAR2(1000),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_agent_reviews UNIQUE (userId, agentId),
    CONSTRAINT fk_agent_reviews_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_reviews_agent FOREIGN KEY (agentId) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE TABLE wishlist (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    propertyId NUMBER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wishlist UNIQUE (userId, propertyId),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_property FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE
);

CREATE TABLE comparisons (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    propertyId1 NUMBER NOT NULL,
    propertyId2 NUMBER NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comparisons_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comparisons_prop1 FOREIGN KEY (propertyId1) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_comparisons_prop2 FOREIGN KEY (propertyId2) REFERENCES properties(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    notifMessage VARCHAR2(1000) NOT NULL,
    notifType VARCHAR2(100),
    isRead NUMBER DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE price_history (
    id NUMBER PRIMARY KEY,
    propertyId NUMBER NOT NULL,
    price NUMBER(15,2) NOT NULL,
    changedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changedBy NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_hist_property FOREIGN KEY (propertyId) REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_price_hist_changer FOREIGN KEY (changedBy) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE search_logs (
    id NUMBER PRIMARY KEY,
    userId NUMBER,
    searchQuery VARCHAR2(1000),
    filters VARCHAR2(1000),
    ipAddress VARCHAR2(50),
    searchedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_search_logs_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE analytics_daily (
    id NUMBER PRIMARY KEY,
    statDate DATE NOT NULL UNIQUE,
    totalProperties NUMBER DEFAULT 0,
    newProperties NUMBER DEFAULT 0,
    totalBookings NUMBER DEFAULT 0,
    totalRevenue NUMBER(15,2) DEFAULT 0.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved_searches (
    id NUMBER PRIMARY KEY,
    userId NUMBER NOT NULL,
    searchName VARCHAR2(255) NOT NULL,
    filters VARCHAR2(1000) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_searches_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
